In [1]:
import pandas as pd
from sqlalchemy import create_engine

In [2]:
# The columns that in the flutter data model
STORED_COLS = ['latitude', 'longitude', 'loc_estimated', 'location_details',
               'title', 'observed', 'classification', 'date', 'season','state','county',
                'moon_phase', 'humidity']

In [15]:
# Load in dataframe, set sighting number as the index / id
df = pd.read_csv('sightings_with_estimates.csv')
df.set_index(df.number.astype(int), inplace=True)
df = df[STORED_COLS]

# add a creature column
df['creature'] = 'Bigfoot'

In [18]:
# create the db connection
engine = create_engine('sqlite:///sightings.db', echo=False)

# drop prev sightings table
engine.execute("DROP TABLE sightings")

# write dataframe to a table
df.to_sql('sightings', con=engine)

# print table columns
engine.execute("SELECT * FROM sightings").keys()

RMKeyView(['number', 'latitude', 'longitude', 'loc_estimated', 'location_details', 'title', 'observed', 'classification', 'date', 'season', 'state', 'county', 'moon_phase', 'humidity', 'creature'])

In [19]:
db=create_engine('sqlite:///sightings.db')
pd.read_sql('select * from sightings',db)

,number,latitude,longitude,loc_estimated,location_details,title,observed,classification,date,season,state,county,moon_phase,humidity,creature
0,438,40.853524,-75.009542,1,"the road is off us rt 80, i dont know the exit...",None,heh i kinda feel a little dumb that im reporti...,Class B,None,Fall,New Jersey,Warren,NaN,NaN,Bigfoot
1,55269,43.415490,-72.330930,0,Close to Claremont down 120 not far from Kings...,Report 55269: Dawn sighting at Stevens Brook o...,I was on my way to Claremont from Lebanon on R...,Class A,2016-06-07,Summer,New Hampshire,Sullivan,0.10,0.79,Bigfoot
2,59757,42.156850,-96.342030,0,Latitude & Longitude : 42.158230 -96.344197,Report 59757: Possible daylight sighting of a ...,I was northeast of Macy Nebraska along the Mis...,Class B,2018-05-25,Spring,Nebraska,Thurston,0.38,0.61,Bigfoot
3,751,48.254220,-101.316600,0,"Ward County, Just outside of a the Minuteman T...",Report 751: Hunter describes described being s...,"While this incident occurred a long time ago, ...",Class A,2000-04-21,Spring,North Dakota,Ward,0.60,0.32,Bigfoot
4,3339,35.748750,-82.261950,0,"Yancey County, North Carolina, near the summit...",Report 3339: Deep impressions seen in the snow,"In early spring 1988, some friends of mine and...",Class B,1988-03-15,Spring,North Carolina,Yancey,0.91,0.79,Bigfoot
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4713,2460,39.192585,-86.239410,1,"Indiana, Brown County, Elkinsville, Lake Monro...",None,My cousin and I were camping way out in the wo...,Class B,None,Spring,Indiana,Brown,NaN,NaN,Bigfoot
4714,2461,39.192585,-86.239410,1,Near Bedford south of Brown County in the Hoos...,None,While backpacking near the horse trails and ac...,Class A,None,Winter,Indiana,Brown,NaN,NaN,Bigfoot
4715,49480,39.179090,-86.335600,0,Yellowood State Park. Off of highway 46 in bet...,Report 49480: Campers hear possible vocalizati...,My wife and I were camping At Yellowood State ...,Class B,2015-08-08,Summer,Indiana,Brown,0.80,0.80,Bigfoot
4716,2459,40.050892,-86.469014,1,On Interstate 65 in Indiana somewhere around t...,None,My wife and I were driving to Indianapolis to ...,Class A,None,Winter,Indiana,Boone,NaN,NaN,Bigfoot
4717,2458,40.472672,-85.323730,1,"Blackford County, Indiana located in the south...",None,It was about 7:00 PM in September. It was stil...,Class B,None,Summer,Indiana,Blackford,NaN,NaN,Bigfoot